This is an exception handling in python